[tool.poetry]
name = "malariagen_data"
version = "0.7.0"
description = "A package for accessing MalariaGEN public data."
authors = ["Alistair Miles <alistair.miles@sanger.ac.uk>", "Chris Clarkson <cc28@sanger.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.9,<3.10"
numpy = "*"
scipy = "*"
pandas = "*"
zarr = "*"
dask = {version="*", extras=["array"]}
fsspec = "*"
gcsfs = "*"
BioPython = "*"
scikit-allel = "*"
xarray = "*"
numba = "*"
matplotlib = "3.3.0"
geos = "^0.2.3"

[tool.poetry.dev-dependencies]
pytest = "*"
notebook = "*"
pre-commit = "*"
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
